# Generated by Django 5.1 on 2024-08-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total_pedido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
