# Generated by Django 5.1 on 2024-08-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_pedido_fecha_alter_pedido_total_pedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallepedido",
            name="estado_pedido",
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="comentario",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
