# Generated by Django 5.1 on 2024-09-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_remove_detallepedido_estado_pedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cedula",
            field=models.CharField(default="0000000000", max_length=13),
        ),
        migrations.AddField(
            model_name="pedido",
            name="nombre",
            field=models.CharField(default="consumidor final", max_length=50),
        ),
        migrations.AlterField(
            model_name="mesa",
            name="numero",
            field=models.IntegerField(unique=True),
        ),
    ]
